### ISSUE TITLE
BE - OTC - kostur projekta

### ISSUE THREAD

**Issue by LukaPavlovicGit** [RAF-SI-2023/Banka-2-Backend#153]
- Generisati spring boot app (Spring initializer) sa potrebnim dependecijima (prve ili druge vezbe)
- Iz bank ili iam servisa prekopirati ostale dependecije
- Updejtovati pom.xml (dodati module za OTC serivis) u root folderu (Bank-2-Backend)
- Po uzoru na prethodne servise odraditi bazicnu konfiguraciju
  - Spring security (pogledati BankService za jwtFiler) 
  - RabbitMQ
  - Naraviti dockerfile
  - Updejtovati docker-compose
- OPCIONO: pogledaj specifikaciju za servis i odradi sta mislis da moze da se odradi

**Comment by adjenadic** [comment]
Urađeno u PR #158
