### ISSUE TITLE
BE - Bank service - rad sa kreditima

### ISSUE THREAD

**Issue by LukaPavlovicGit** [RAF-SI-2023/Banka-2-Backend#160]
Omoguciti rad sa kreditima. Stranice 95-100 u [specifikaciji](https://docs.google.com/document/d/1dYuzetjCghWvhnTkTDrqz5Ze9q2b_Tpt/edit)

**Comment by GajicM** [comment]
dodati krediti i zahtevi za podnosenje kredita  u bank servis, ostalo jos kreiranje credita bas
i logika za security da se odradi, dodato nesto malo u bootstrap da mogu da se testiraju metode...
trebalo bi sutra da zavrsim ako ne bude problema 
https://github.com/GajicM/Banka-2-Backend/commit/a2086f7606cd232720aa99a5881285fdc9b5d062
