### ISSUE TITLE
BE - Stock service - integracioni i unit testovi za future contracts

### ISSUE THREAD

**Issue by LukaPavlovicGit** [RAF-SI-2023/Banka-2-Backend#172]
- Odraditi unit i integracione testove za Future contract. Pokriti sto vise slucajeva. Svi testozvi moraju da rade na predvidjen nacin

**Comment by adjenadic** [comment]
@LukaPavlovicGit @Mixxx29 Treba uraditi i Controller, mora da se uradi do prekosutra kako bi stigli da povežemo!
