### ISSUE TITLE
BE - OTC Service - trgovina izmedju banaka

### ISSUE THREAD

**Issue by LukaPavlovicGit** [RAF-SI-2023/Banka-2-Backend#316]
## Opis funkcionalnosti
Omoguciti trgovinu akcijama izmedju dve banke (mi saradjujemo sa bankom1)

## Smernice
* Obratiti se Milosu Damjanovicu (on je u specifikacionom timu, i smislio je mehanizam) za sve informacije i nedoumice
* Iskomunicirati sa clanovima iz Banka1 koji rade na ovoj funkcionalnosti radi utvrdjivanja protokola i ostalih stvari
* Sto se nejasnoca u koda tice komunicirajte sa ljudima koji su pisali taj kod

## Testovi
* Unit (coverage mora da bude preko 80%)
* Integracioni
* E2E

## Napomena
- [KAKO DA VIDIM TEST COVERAGE ?](https://drive.google.com/file/d/1yssmvYN4lvGWQEGQFbTAOl5txT3kuBRW/view?usp=drive_link)

**Comment by adjenadic** [comment]
Trgovina između banke 2 i banke 3 odrađena; ostalo je da se doradi skidanje novca sa bankovnog računa.
